import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "@/node_modules/next/link";

import { fontSans } from "@/lib/fonts";
const inter = Inter({ subsets: ["latin"] });

import { MainNav } from "@/components/main-nav";
import MobileNav from "@/components/mobile-nav";
import { buttonVariants } from "@/components/ui/button";
import { ModeToggle } from "@/components/toggle";
import { SiteFooter } from "@/components/site-footer";
import { MobileToggle } from "@/components/mobile-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex min-h-screen flex-col">
        <header className="h-16 sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="flex h-16 items-center justify-between py-6 w-full px-[4%] lg:px-[7%]">
            <MobileNav />
            <MainNav />
            <nav>
              <div className="md:flex">
                <div className="flex items-center">
                  <ModeToggle />
                  <Link
                    href="/login"
                    className={cn(
                      buttonVariants({ variant: "default", size: "sm" }),
                      "px-4"
                    )}
                  >
                    Get Started
                  </Link>
                  <MobileToggle />
                </div>
              </div>
            </nav>
          </div>
        </header>
        {/* <HeroPage /> */}

        <main className="flex-1">{children}</main>
      </div>

      <SiteFooter />
    </>
  );
}
